import type { Metadata } from "next";
import "./style.css";

export const metadata: Metadata = {
  title: "Rota da Cerveja | Sobre",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <main className="about-wrapper">
      <img className="about-img" src="/api/image?name=about&type=public"></img>
      <h1 className="title">Sobre a Rota da Cerveja</h1>
      <p className="about-paragraphic max-w-screen-md mx-auto mt-10 text-center indent-0">
        A Rota da Cerveja é uma plataforma online dedicada a conectar amantes de cerveja artesanal com cervejarias locais. Nosso objetivo é proporcionar uma experiência única, onde os usuários podem explorar e desfrutar de uma variedade de cervejas de alta qualidade, enquanto aprendem sobre a cultura cervejeira e se conectam diretamente com os produtores.
      </p>
      <section className="about-section-container">
        <section className="about-section">
          <h2 className="about-subtitle">Conexão Autêntica entre Apreciadores e Produtores</h2>
          <p className="about-paragraphic">
            O Rota da Cerveja nasceu do desejo de estabelecer uma ponte genuína entre os amantes de cerveja artesanal e as cervejarias locais. Nosso objetivo é criar um sistema web que não só permita aos usuários explorar e desfrutar de uma variedade de cervejas de alta qualidade, mas também promova um relacionamento mais direto e interativo entre consumidores e produtores.
          </p>
        </section>
        <section className="about-section">
          <h2 className="about-subtitle">Guia Informativo e Personalizado</h2>
          <p className="about-paragraphic">
            A plataforma atua como um guia informativo e de recomendações, incentivando a descoberta de novos sabores e enriquecendo o conhecimento sobre a diversidade de cervejas artesanais. Compreendemos as preferências e hábitos de consumo dos nossos usuários, oferecendo uma experiência personalizada e recomendações alinhadas com os gostos individuais.
          </p>
        </section>
        <section className="about-section">
          <h2 className="about-subtitle">Exclusividade e Comunidade</h2>
          <p className="about-paragraphic">
          Desenvolvemos um espaço exclusivo, semelhante a um clube privado, onde os usuários podem interagir e compartilhar experiências relacionadas à cerveja artesanal. A plataforma permite que os usuários explorem virtualmente cervejarias, conheçam suas histórias e métodos de produção, e participem de experiências imersivas.
          </p>
        </section>
        <section className="about-section">
          <h2 className="about-subtitle">Valorização da Cultura Cervejeira Brasileira</h2>
          <p className="about-paragraphic">
          Nosso projeto visa promover uma apreciação mais profunda da diversidade de sabores do Brasil, valorizando a riqueza cultural e a diversidade das cervejas artesanais brasileiras.
          </p>
        </section>
        <section className="about-section">
          <h2 className="about-subtitle">Base Sólida e Benefícios Exclusivos</h2>
          <p className="about-paragraphic">
          Utilizamos dados oficiais e artigos acadêmicos para orientar o desenvolvimento da plataforma. Os usuários terão benefícios exclusivos, como descontos, eventos especiais e acesso antecipado a novos lançamentos.
          </p>
        </section>
        <section className="about-section">
          <h2 className="about-subtitle">Recomendações Personalizadas e Avaliação Contínua</h2>
          <p className="about-paragraphic">
          Analisamos as preferências dos usuários para fornecer recomendações personalizadas de cervejas artesanais. A eficácia das conexões entre usuários e cervejarias é avaliada regularmente para garantir acesso a uma variedade de cervejas de qualidade. A satisfação dos usuários é verificada constantemente para assegurar a excelência do nosso serviço.
          </p>
        </section>
      </section>
    </main>
  );
}
